In [2]:
with open("inputs/day16-input.txt") as f:
    puzzle = list(map(int, f.read().strip()))

## Part 1

In [4]:
%%time

from itertools import cycle
from typing import List
import numpy as np

def pattern(index: int, length: int) -> List[int]:
    l = np.repeat([0, 1, 0, -1], [index] * 4)
    
    repeat = (length + 1) // (index * 4) + 1
    p = np.tile(l, repeat)
    
    return p[1:length + 1]


def pattern_matrix(length: int):
    columns = [pattern(i + 1, length) for i in range(length)]
    return np.stack(columns)


signal = puzzle
matrix = pattern_matrix(len(puzzle))

for _ in range(100):
    signal = np.abs(matrix @ signal) % 10

print("".join(map(str, signal[:8])))

53296082
CPU times: user 318 ms, sys: 210 ms, total: 528 ms
Wall time: 300 ms


## Part 2

In [54]:
%%time

# [[ 1  0 -1  0  1  0 -1  0]
# [ 0  1  1  0  0 -1 -1  0]
# [ 0  0  1  1  1  0  0  0]
# [ 0  0  0  1  1  1  1  0]
# [ 0  0  0  0  1  1  1  1]
# [ 0  0  0  0  0  1  1  1]
# [ 0  0  0  0  0  0  1  1]
# [ 0  0  0  0  0  0  0  1]]
# Lower half is a triangular matrix only

signal = np.tile(puzzle, 10_000)
offset = int("".join(map(str, signal[:7])))
signal = signal[offset:]
signal_length = len(signal)

#matrix = np.tri(signal_length - offset, signal_length - offset, k=-offset, dtype=int).transpose()

for _ in range(100):
    for i in range(signal_length - 2, -1, -1):
        signal[i] += signal[i + 1]
    signal %= 10
    
print("".join(map(str, signal[:8])))

43310035
CPU times: user 30.3 s, sys: 13.8 ms, total: 30.4 s
Wall time: 30.4 s
